#       ######## ######## ##     ## ########  ##          ###    ######## ########      #
#          ##    ##       ###   ### ##     ## ##         ## ##      ##    ##            #
#          ##    ##       #### #### ##     ## ##        ##   ##     ##    ##            #
#          ##    ######   ## ### ## ########  ##       ##     ##    ##    ######        #
#          ##    ##       ##     ## ##        ##       #########    ##    ##            #
#          ##    ##       ##     ## ##        ##       ##     ##    ##    ##            #
#          ##    ######## ##     ## ##        ######## ##     ##    ##    ########      # 

#        ######  ######## ##    ##  ######   #######  ########  ######## ##    ##       #
#       ##    ## ##       ###   ## ##    ## ##     ## ##     ## ##       ###   ##       #
#       ##       ##       ####  ## ##       ##     ## ##     ## ##       ####  ##       #
#        ######  ######   ## ## ##  ######  ##     ## ########  ######   ## ## ##       #
#             ## ##       ##  ####       ## ##     ## ##   ##   ##       ##  ####       #
#       ##    ## ##       ##   ### ##    ## ##     ## ##    ##  ##       ##   ###       #
#        ######  ######## ##    ##  ######   #######  ##     ## ######## ##    ##       #

#########################################################################################
#---------------------------------------------------------------------------------------#
##---------------------------- AKTUELLE ZEIT UND DATUM --------------------------------##
#---------------------------------------------------------------------------------------#
#########################################################################################

sensor:
#-----------------------------------------------------------
# Dashboard Datum und Uhrzeit
#-----------------------------------------------------------
- name: Datum und Uhrzeit
  unique_id: datum_uhrzeit
  icon: mdi:calendar-today          
  state: >
    {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"] %}
    {% set days = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"]  %}
    Heute ist {{ days[now().weekday()] + ', der ' + now().day | string + '. ' + months[now().month-1] }} und es ist {{ states('sensor.time') }} Uhr

#-----------------------------------------------------------
# Mein Datum
#-----------------------------------------------------------
- name: Aktuelles Datum
  unique_id: mein_datum
  icon: mdi:calendar-today          
  state: >
    {% set months = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"] %}
    {% set days = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"]  %}
    {{ days[now().weekday()] + ', ' + now().day | string + '.' + months[now().month-1] + ' ' + now().year | string }}

#-----------------------------------------------------------
# Mein Datum kurz
#-----------------------------------------------------------
- name: Aktuelles Datum Kurz
  unique_id: mein_datum_kurz
  icon: mdi:calendar-today          
  state: >
    {{ now().day | string + '.' + now().month | string + '.' + now().year | string }}

#-----------------------------------------------------------
# Meine Zeit
#-----------------------------------------------------------
- name: "Aktuelle Uhrzeit"
  unique_id: meine_zeit
  icon: mdi:account-clock-outline
  state: >
    {{ states('sensor.time') }} Uhr