#       ######## ######## ##     ## ########  ##          ###    ######## ########      #
#          ##    ##       ###   ### ##     ## ##         ## ##      ##    ##            #
#          ##    ##       #### #### ##     ## ##        ##   ##     ##    ##            #
#          ##    ######   ## ### ## ########  ##       ##     ##    ##    ######        #
#          ##    ##       ##     ## ##        ##       #########    ##    ##            #
#          ##    ##       ##     ## ##        ##       ##     ##    ##    ##            #
#          ##    ######## ##     ## ##        ######## ##     ##    ##    ########      # 

#        ######  ######## ##    ##  ######   #######  ########  ######## ##    ##       #
#       ##    ## ##       ###   ## ##    ## ##     ## ##     ## ##       ###   ##       #
#       ##       ##       ####  ## ##       ##     ## ##     ## ##       ####  ##       #
#        ######  ######   ## ## ##  ######  ##     ## ########  ######   ## ## ##       #
#             ## ##       ##  ####       ## ##     ## ##   ##   ##       ##  ####       #
#       ##    ## ##       ##   ### ##    ## ##     ## ##    ##  ##       ##   ###       #
#        ######  ######## ##    ##  ######   #######  ##     ## ######## ##    ##       #

#########################################################################################
#---------------------------------------------------------------------------------------#
##------------------------- Tageslicht Transparenz Sensor -----------------------------##
#---------------------------------------------------------------------------------------#
#########################################################################################

sensor:

#-----------------------------------------------------------
# SONNENLICHT HELLIGKEIT BERECHNET
#-----------------------------------------------------------
- name: Sonnenlicht berechnet
  unique_id: sonnenlicht_berechent
  icon: mdi:sun-angle-outline
  state: >
    {%- set elevation = states('sensor.sun_solar_elevation') | float %}
    {%- set cloud_coverage = states('sensor.openweathermap_cloud_coverage') | float %}
    {%- set cloud_factor = (1 - (0.75 * ( cloud_coverage / 100) ** 3 )) %}
    {%- set min_elevation = -6 %}
    {%- set max_elevation = 65 %}
    {%- set adjusted_elevation = elevation - min_elevation %}
    {%- set adjusted_elevation = [adjusted_elevation,0] | max %}
    {%- set adjusted_elevation = [adjusted_elevation,max_elevation - min_elevation] | min %}
    {%- set adjusted_elevation = adjusted_elevation / (max_elevation - min_elevation) %}
    {%- set adjusted_elevation = adjusted_elevation %}
    {%- set adjusted_elevation = adjusted_elevation * 100 %}
    {%- set brightness = adjusted_elevation * cloud_factor %}
    {{ brightness | round }}
  unit_of_measurement: 'lx'
  device_class: 'illuminance'

#-----------------------------------------------------------
# TRANSPARENZ BERECHNUNG
#-----------------------------------------------------------
- name: Sonnenlicht Transparenz
  unique_id: sonnenlicht_transparenz
  icon: mdi:sun-clock-outline
  state: >
    {%- set sunpct = states('sensor.sonnenlicht_berechnet') | float %}
    {%- set opacity = sunpct / 100 | float %}
    {{ opacity }}


#-----------------------------------------------------------
# Sommer/Winter/Tageslicht
#-----------------------------------------------------------
- name: Sommer-Winter-Tageslicht
  unique_id: sommer_winter_tageslicht
  icon: mdi:sun-clock-outline
  state: >
    {%- set somwin = states('switch.hauptschalter_heizung') %}
    {%- set tagnacht = states('sun.sun') %}
    {%- set xmas = states.calendar.advent_advent.attributes.message %}
    {% if somwin == "off" and tagnacht == "above_horizon" %}
      SOMTAG
    {% elif somwin == "on" and tagnacht == "above_horizon" and xmas != "XMAS" %}
      WINTAG
    {% elif somwin == "on" and tagnacht == "above_horizon" and xmas == "XMAS" %}
      WEIHTAG
    {% elif somwin == "off" and tagnacht == "below_horizon" %}
      SOMNACHT
    {% elif somwin == "on" and tagnacht == "below_horizon" and xmas != "XMAS" %}
      WINNACHT
    {% elif somwin == "on" and tagnacht == "below_horizon" and xmas == "XMAS" %}
      WEIHNACHT
    {% endif %}